# Generated by Django 3.2.25 on 2024-04-06 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название книги')),
                ('author', models.CharField(max_length=200, verbose_name='Автор')),
                ('description', models.TextField(verbose_name='Описание')),
                ('year_of_issue', models.IntegerField(max_length=4, verbose_name='Год выпуска')),
                ('availability', models.IntegerField(max_length=3, verbose_name='Наличие в библиотеке')),
                ('image', models.ImageField(upload_to='books/image/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'ordering': ('-name',),
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название тега')),
                ('color', models.CharField(max_length=7, unique=True, verbose_name='Цвет')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
                'ordering': ('-name',),
            },
        ),
        migrations.CreateModel(
            name='GenregBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book', verbose_name='Книга')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.genre', verbose_name='Жанр')),
            ],
        ),
        migrations.AddConstraint(
            model_name='genregbook',
            constraint=models.UniqueConstraint(fields=('book', 'genre'), name='book_genre_unique'),
        ),
    ]
