# Generated by Django 3.2.25 on 2024-04-06 19:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='availability',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Наличие в библиотеке'),
        ),
        migrations.AlterField(
            model_name='book',
            name='year_of_issue',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(4)], verbose_name='Год выпуска'),
        ),
    ]
