# Generated by Django 3.2.25 on 2025-07-01 13:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(blank=True, through='books.AuthorBook', to='books.Author', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='book',
            name='year_of_issue',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(2025)], verbose_name='Год выпуска'),
        ),
    ]
