# Generated by Django 3.2.3 on 2024-04-20 10:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(null=True, upload_to='books/image/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='book',
            name='year_of_issue',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(2024)], verbose_name='Год выпуска'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Название жанра'),
        ),
    ]
