# Generated by Django 3.2.25 on 2025-07-07 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20250707_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='Slug_book'),
        ),
    ]
