# Generated by Django 3.2.3 on 2024-04-20 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20240420_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genres',
            field=models.ManyToManyField(blank=True, to='books.Genre', verbose_name='Жанры'),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Название книги'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='color',
            field=models.CharField(max_length=7, verbose_name='Цвет'),
        ),
    ]
