# Generated by Django 3.2.25 on 2025-08-11 07:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_author_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='availability',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Наличие'),
        ),
        migrations.AlterField(
            model_name='book',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата поступления'),
        ),
    ]
