# Generated by Django 3.2.3 on 2024-04-20 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20240420_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, upload_to='books/image/', verbose_name='Изображение'),
        ),
    ]
